import React from 'react'
import Forms from '@/components/forms'
import Head from 'next/head'

function forms() {
  return (
    <>
    <Head>
    <title>Re-Haul</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <Forms />
    </>
  )
}

export default forms