import Head from 'next/head'
import Slides from '@/components/slideshow'
import Courses from '@/components/courses'

export default function Home() {
  return (
    <>
      <Head>
        <title>Re-Haul</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slides/>
      <Courses />
    </>
  )
}
